name: gh-deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository with full history (fetch-depth: 0)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # Setup Python 3.13 environment
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      
      # Install dependencies from requirements file
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-mkdocs.txt
      
      # Deploy the site using mkdocs
      - name: Deploy with MkDocs
        run: mkdocs gh-deploy --force
